### ISSUE TITLE
Trailing slash even though url_suffix is empty

### ISSUE THREAD

**Issue by obendev** [terminal42/contao-changelanguage#188]
I may have found a bug.
If you set the following in the config.yml
```yml
contao: 
    url_suffix: ''
    prepend_locale: true
```
the extension puts a trailing slash behind the language instead of not setting any.
For example: `domain.tld/en/` instead of `domain.tld/en`.
The second variant without a suffix should be the right one because of `url_suffix: ''` - no suffix or trailing slash should actually be set.

contao/core-bundle 4.4.54
terminal42/contao-changelanguage 3.1.14
